name: 'C++ API Documentation'
description: 'Generate and publish Doxygen documentation'
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  version:
    description: 'Version to publish'
    required: false
  repo-name:
    description: 'Repository name'
    required: true
  github-token:
    description: 'GitHub token for deployment and triggering central documentation update'
    required: true

runs:
  using: "composite"
  steps:

    - name: Show Action Version
      shell: bash
      run: |
        echo "::group::Action Version Info"
        echo "Using keypop-actions version: ${{ env.GITHUB_ACTION_REF }}"
        echo "SHA: ${{ github.sha }}"
        echo "Action path: ${{ github.action_path }}"
        echo "::endgroup::"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      shell: bash
      run: |
        echo "Installing Python dependencies from ${{ github.action_path }}/scripts/requirements.txt"
        python -m pip install --upgrade pip
        pip install -r "${{ github.action_path }}/scripts/requirements.txt"

    - name: Check version
      if: inputs.version != ''
      shell: bash
      run: python ${{ github.action_path }}/scripts/check_version.py "${{ inputs.version }}"

    - name: Patch Doxyfile
      if: always()
      shell: bash
      run: python ${{ github.action_path }}/scripts/patch_doxyfile.py "/home/runner/work/${{ inputs.repo-name }}/${{ inputs.repo-name }}/.github/doxygen/Doxyfile" "${{ inputs.version }}"

    - name: Copy Doxyfile and logo.svg
      shell: bash
      run: |
        echo "Copying logo.svg from ${{ github.action_path }}/doxygen/ to /home/runner/work/${{ inputs.repo-name }}/${{ inputs.repo-name }}/.github/doxygen/"
        cp -r "${{ github.action_path }}/doxygen/." "/home/runner/work/${{ inputs.repo-name }}/${{ inputs.repo-name }}/.github/doxygen/"

    - name: Generate documentation
      uses: mattnotmitt/doxygen-action@v1.9.2
      with:
        working-directory: .github/doxygen/
        doxyfile-path: ./Doxyfile

    - name: Prepare documentation
      shell: bash
      run: |
        python ${{ github.action_path }}/scripts/prepare_documentation.py \
          --github-org ${GITHUB_REPOSITORY_OWNER} \
          --repo-name "${{ inputs.repo-name }}" \
          --version "${{ inputs.version }}"

    - name: Deploy to doc branch
      shell: bash
      working-directory: ${{ inputs.repo-name }}
      run: |
        git config user.name "Eclipse Keypop Bot"
        git config user.email "${{ inputs.repo-name }}-bot@eclipse.org"
        git remote set-url origin "https://x-access-token:${{ inputs.github-token }}@github.com/${GITHUB_REPOSITORY}.git"
        git add .
        if [ -n "${{ inputs.version }}" ]; then
          git commit -m "docs: update ${{ inputs.version }} documentation"
        else
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: update snapshot documentation"
        fi
        git push origin doc --force

    - name: Trigger central documentation update
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ inputs.github-token }}
        repository: eclipse-keypop/keypop-api-docs
        event-type: update-submodules